### ISSUE TITLE
[step1] - Project plan

### ISSUE THREAD

**Issue by jjaderg** [jjaderg/view-awesome#1]
### Checklist:

- [ ] Describe the installation
- [ ] Implement TravisCI and your badges
- [ ] Create Header component
- [ ] Create Search component
- [ ] Create Card component
